set nocompatible                  " disable vi compatibility

silent! call pathogen#runtime_append_all_bundles()  " have pathogen install all bundles
silent! call pathogen#helptags()                    " and then generate help for all bundles

syntax enable                     " enable syntax highlighting
filetype plugin indent on         " turn on filetype detection and load plugin and indent files

runtime macros/matchit.vim        " enable % to bounce between matching structures (e.g. def/end)

set showcmd                       " show info on incomplete commands (e.g num lines selected in visual mode)
set showmode                      " display what mode you are in

set backspace=indent,eol,start    " more intuitive backspacing

set hidden                        " do not unload abandoned buffers

set wildmenu                      " better command-line completion, go up/down dirs etc.
set wildmode=list:longest         " complete to longest common substring (like a shell does)

set ignorecase                    " ignore case of letters when searching
set smartcase                     " override ignorecase if one or more upper case chars used

set number                        " show line numberings
set ruler                         " show line and column numbers

set list                          " show invisibles
set listchars=tab:→\ ,trail:⋅     " use these characters for invisibles

set incsearch                     " match strings as you type
set hlsearch                      " highlight the matched string

set wrap                          " wrap lines if they are longer than the width of the window
set scrolloff=3                   " keep this number of lines displayed above or below the cursor

set title                         " display filename and modified flags

set visualbell                    " turn off beeping

set nobackup                      " do not make a backup of a file before overwriting it
set nowritebackup                 " same as above
set directory=$HOME/.vim/tmp//,.  " keep swap files in one place
if version >= 730
  " persistent undo
  set undodir=$HOME/.vim/tmp
  set undofile
endif

set tabstop=2                     " number of spaces a tab counts for
set shiftwidth=2                  " number of spaces to use for each level of autoindent
set expandtab                     " always use spaces instead of tabs

set laststatus=2                  " show the status line
" [<buffer number>] <possibly truncated file path> <buffer, filetype and modified flags> <line and column numbers> <percentage through file>
set statusline=\ %<%.99f\ %{fugitive#statusline()}\ %h%w%m%r%y\ %=%-16(\ %l,%c-%v\ %)%P

set t_Co=256 " enable 256 colors
colorscheme blackboard
" use these colors for invisibles
highlight NonText ctermfg=white guifg=#4a4a59
highlight SpecialKey ctermfg=white guifg=#4a4a59

" location of dictionary on Mac OS X
set dictionary=/usr/share/dict/words

" for the makegreen plugin, enable rspec support
autocmd BufNewFile,BufRead *_spec.rb compiler rspec

" display bookmarks in NERDTree
let NERDTreeShowBookmarks=1
" toggle NERDTree drawer
nmap <silent> <Leader>d :execute 'NERDTreeToggle ' . getcwd()<CR>
" always show hidden files in NERDTree
let NERDTreeShowHidden=1
